server:
  port: 8099
  servlet:
    context-path: /manager_jj
#  devtools
debug: true
spring:
  devtools:
    restart:
      enabled: false
  redis:
    # Redis数据库索引（默认为 0）
    database: 5
    # Redis服务器地址
    host: 192.168.1.55
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
  datasource:
    dynamic:
      primary: jj
      datasource:
        jj:
          url: jdbc:mysql://127.0.0.1:3306/persie_value?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: chufan123
        fc:
          url: jdbc:mysql://127.0.0.1:3306/persie_value?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: chufan123
mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:/mybatis-mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml
