server:
  port: 8888
  servlet:
    context-path: /manage
    session:
      timeout: 60m

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: Asia/Shanghai
  rabbitmq:
    password: mahalo.server
    username: root
    host: 192.168.1.246
    port: 5672
primary:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.246:3306/fishmanagerv5?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true
      username: root
      password: root
      minIdle: 1
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
second:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.246:3306/fishv5?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true
      username: root
      password: root
      minIdle: 1
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
config:
  upload: d:/upload/normal
  domain: http://192.168.1.126:8888/upload/
  excelSave: d:/upload/excel