server:
  port: 8098
  servlet:
    context-path: /manager_system
#  devtools
debug: true
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.201.174:3306/manager_system?characterEncoding=utf-8&mysqlEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: chufan
    password: chufan123
    druid:
      filters: stat
      minIdle: 1
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
mybatis:
  mapper-locations: classpath:mybatis-mapper/**/*.xml
  type-aliases-package: com.cc.manager.modules.sys.entity
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml

config:
  timeout: 7200